### ISSUE TITLE
Update README with Develop section with build instructions

### ISSUE THREAD

**Issue by adityakamble49** [dragonriders/word-list-web#1]
Update README with Develop section with build instructions
- Use Markdown properly for command instructions
- Start to end build process for application
- Include prerequisites

**Comment by adityakamble49** [comment]
Did `npm install` to install dependencies
But **not** able to use `ng serve`. Getting following error.
```
$ echo %cd%       <- Current Directory
D:\workspace\d\word-list-web
$ ng serve
You have to be inside an angular-cli project in order to use the serve command.
```

**Comment by ardnahcivar** [comment]
added the prerequisites and getting started in README.md , please take a look at it and check by running the application.

**Comment by adityakamble49** [comment]
Checked updated README. replaced quotes by code markdown for commands and code snippets
Given instructions are working
